// <auto-generated />
using FourChanGrabber.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FourChanGrabber.Migrations
{
    [DbContext(typeof(MediaDbContext))]
    [Migration("20260419171525_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FourChanGrabber.Data.Models.DownloadQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ImageSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("TargetPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImageSourceId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_DownloadQueue_Status");

                    b.ToTable("DownloadQueue", (string)null);
                });

            modelBuilder.Entity("FourChanGrabber.Data.Models.ImageSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ImageSource", (string)null);
                });

            modelBuilder.Entity("FourChanGrabber.Data.Models.MediaData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SavePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImageSourceId")
                        .HasDatabaseName("IX_MediaData_ImageSourceId");

                    b.ToTable("MediaData", (string)null);
                });

            modelBuilder.Entity("FourChanGrabber.Data.Models.DownloadQueue", b =>
                {
                    b.HasOne("FourChanGrabber.Data.Models.ImageSource", "ImageSource")
                        .WithMany()
                        .HasForeignKey("ImageSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageSource");
                });

            modelBuilder.Entity("FourChanGrabber.Data.Models.MediaData", b =>
                {
                    b.HasOne("FourChanGrabber.Data.Models.ImageSource", "ImageSource")
                        .WithMany()
                        .HasForeignKey("ImageSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageSource");
                });
#pragma warning restore 612, 618
        }
    }
}
